# .container.registry targets the container registry for pulling the image
# .container.image is the specific image that's gonna be used
image:
  name: localhost:5000/eveid-ui
  # should be overrided ex: rc-v0.0.1_landing-preview
  version: latest

server:
  port: 3001

# environment is used to determine the namespace
cluster:
  env: "dev"
